/**
 * Image Generation Keywords
 * 
 * Multi-language keywords for detecting image generation requests.
 * Supports Turkish, Persian (Farsi), and English.
 * 
 * @module chat/constants/image-keywords
 * @description Single Responsibility: Only contains image detection keywords
 */

// ==================== TÜRKÇE ====================
const TURKISH_IMAGE_KEYWORDS = [
  // Fiil kombinasyonları
  'resim yap',
  'resmi yap',
  'resimi yap',
  // Yaygın yazım hataları
  'resim ypa',  // typo: ypa -> yap
  'resmi ypa',
  'resimi ypa',
  'resim yao',  // typo: yao -> yap
  'resmi yao',
  'resim uap',  // typo: uap -> yap
  'resmi uap',
  'resim çzi',  // typo: çzi -> çiz
  'resmi çzi',
  'resim yapı',  // typo
  'resmi yapı',
  'resim yaop',  // typo
  'resmi yaop',
  // Normal keywords devam
  'resim yapar mısın',
  'resmi yapar mısın',
  'resimi yapar mısın',
  'resim yaparmısın',
  'resmi yaparmısın',
  'resimi yaparmısın',
  'resim oluştur',
  'resmi oluştur',
  'resim çiz',
  'resmi çiz',
  'görsel yap',
  'görseli yap',
  'görsel oluştur',
  'görseli oluştur',
  'görsel çiz',
  'görseli çiz',
  'fotoğraf yap',
  'fotoğrafı yap',
  'fotoğrafını yap',
  'fotoğraf oluştur',
  'fotoğraf çiz',
  'resimini yap',
  'resmini yap',
  // İstek cümleleri
  'bir resim',
  'bana resim',
  'bana bir resim',
  'bana görsel',
  'bana bir görsel',
  'bana fotoğraf',
  'benim için resim',
  'benim için görsel',
  'resim istiyorum',
  'görsel istiyorum',
  'resim lazım',
  'görsel lazım',
  'resim ver',
  'görsel ver',
  'resim gönder',
  'görsel gönder',
  'resim üret',
  'görsel üret',
  'resim tasarla',
  'görsel tasarla',
  // Soru formları
  'resim yapabilir misin',
  'görsel yapabilir misin',
  'resim oluşturabilir misin',
  'görsel oluşturabilir misin',
  'resim çizebilir misin',
  'görsel çizebilir misin',
  'resim yapar mısın',
  'görsel yapar mısın',
  // Tekil kelimeler
  'görsel',
  'çiz',
  'illüstrasyon',
  'grafik',
  'manzara',
  'portre',
  'karikatür',
  'anime',
  'logo',
  'ikon',
  'afiş',
  'poster',
  'kapak',
  'avatar',
  'karakter',
  'sahne',
  'tasarım',
  'eskiz',
  'taslak',
];

// ==================== FARSÇA (فارسی) ====================
const PERSIAN_IMAGE_KEYWORDS = [
  // Fiil kombinasyonları
  'تصویر بساز',
  'عکس بساز',
  'تصویر بکش',
  'عکس بکش',
  'تصویر درست کن',
  'عکس درست کن',
  'تصویر ایجاد کن',
  'عکس ایجاد کن',
  'نقاشی کن',
  'نقاشی بکش',
  'طراحی کن',
  'طراحی بکش',
  // İstek cümleleri
  'یک تصویر',
  'یه تصویر',
  'یک عکس',
  'یه عکس',
  'برام تصویر',
  'برایم تصویر',
  'برام عکس',
  'برایم عکس',
  'تصویر بده',
  'عکس بده',
  'تصویر میخوام',
  'عکس میخوام',
  'تصویر می‌خوام',
  'عکس می‌خوام',
  'تصویر لازم دارم',
  'عکس لازم دارم',
  'تصویر میخواهم',
  'عکس میخواهم',
  // Soru formları
  'تصویر میسازی',
  'عکس میسازی',
  'تصویر می‌سازی',
  'عکس می‌سازی',
  'میتونی تصویر',
  'میتونی عکس',
  'می‌تونی تصویر',
  'می‌تونی عکس',
  'میشه تصویر',
  'میشه عکس',
  'می‌شه تصویر',
  'می‌شه عکس',
  // Tekil kelimeler
  'تصویر',
  'عکس',
  'بساز',
  'بکش',
  'نقاشی',
  'طراحی',
  'ایجاد',
  'گرافیک',
  'پوستر',
  'لوگو',
  'آیکون',
  'کاراکتر',
  'صحنه',
  'منظره',
  'چهره',
  'پرتره',
  'انیمه',
  'کارتون',
  'اسکیس',
  'طرح',
];

// ==================== İNGİLİZCE (English) ====================
const ENGLISH_IMAGE_KEYWORDS = [
  // Verb combinations
  'create image',
  'create a image',
  'create an image',
  'create picture',
  'create a picture',
  'create photo',
  'create a photo',
  'generate image',
  'generate a image',
  'generate an image',
  'generate picture',
  'generate a picture',
  'generate photo',
  'draw image',
  'draw a image',
  'draw an image',
  'draw picture',
  'draw a picture',
  'draw me',
  'draw a',
  'draw an',
  'make image',
  'make a image',
  'make an image',
  'make picture',
  'make a picture',
  'make me a',
  'make me an',
  // Request phrases
  'i want image',
  'i want a image',
  'i want an image',
  'i want picture',
  'i want a picture',
  'i need image',
  'i need a image',
  'i need an image',
  'i need picture',
  'give me image',
  'give me a image',
  'give me an image',
  'give me picture',
  'show me image',
  'show me a image',
  'show me an image',
  'show me picture',
  // Question forms
  'can you create',
  'can you generate',
  'can you draw',
  'can you make',
  'could you create',
  'could you generate',
  'could you draw',
  'would you create',
  'would you draw',
  'please create',
  'please generate',
  'please draw',
  // Single keywords
  'image',
  'picture',
  'photo',
  'photograph',
  'draw',
  'paint',
  'sketch',
  'illustration',
  'artwork',
  'design',
  'graphic',
  'poster',
  'logo',
  'icon',
  'avatar',
  'character',
  'scene',
  'landscape',
  'portrait',
  'anime',
  'cartoon',
  'render',
  'visualize',
  'depict',
  'illustrate',
  'concept art',
  'digital art',
  'fan art',
  'wallpaper',
  'banner',
  'thumbnail',
  'cover art',
  'album art',
  'book cover',
  'movie poster',
];

/**
 * All image generation keywords combined
 * Used to detect if a user message is requesting image generation
 */
export const IMAGE_KEYWORDS: readonly string[] = [
  ...TURKISH_IMAGE_KEYWORDS,
  ...PERSIAN_IMAGE_KEYWORDS,
  ...ENGLISH_IMAGE_KEYWORDS,
] as const;

/**
 * Check if a message contains image generation keywords
 * @param message - The user message to check
 * @returns true if the message likely requests image generation
 */
export function containsImageKeyword(message: string): boolean {
  const lowerMessage = message.toLowerCase();
  return IMAGE_KEYWORDS.some((keyword) => lowerMessage.includes(keyword));
}
